
import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/src/components/ui/sidebar";
import { SideBarApp } from "@/src/components/layout";
import QueryProvider from "@/src/app/providers/query-provider";
import { Toaster } from "sonner";
import { auth } from "@/src/features/auth/auth";
import { SessionProvider } from "next-auth/react"


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased dark`}
    >
      <body>
        <SidebarProvider>
          <SessionProvider>
            <SideBarApp />
            <SidebarInset>
              <SidebarTrigger />
              <Toaster />
              <main>
                <QueryProvider>

                  {children}
                </QueryProvider>
              </main>
            </SidebarInset>
          </SessionProvider>

        </SidebarProvider>

      </body>
    </html>
  );
}

