services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: streaming_video
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    build:
      context: .
      dockerfile: dockerfile-rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
      - '15692:15692'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mongo_data:
  rabbitmq-data:
