FROM node:20-alpine AS base
RUN npm install -g pnpm

FROM base AS deps

WORKDIR /app
COPY be/package.json  ./fe/
COPY shared/package.json  ./shared/

COPY pnpm-lock.yaml pnpm-workspace.yaml ./
RUN CI=true 
RUN pnpm install

COPY fe ./fe
COPY shared ./shared

FROM base AS builder
WORKDIR /app
COPY --from=deps /app ./

WORKDIR /app/fe

RUN pnpm build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/fe/.next/ ./

COPY --from=builder /app/fe/public ./public

EXPOSE 3000

CMD ["node", "standalone/fe/server.js"]